version: '2'
services:

    # btc is an image of bitcoin node which used as base image for btcd and
    # btccli. The environment variables default values determined on stage of
    # container start within starting script.
    # btc:
    #   image: btcd
    #   build:
    #     context: btcd/
    #   volumes:
    #         - shared:/rpc
    #         - bitcoin:/data
    #   environment:
    #     - RPCUSER
    #     - RPCPASS
    #     - NETWORK

    # btcd:
    #     extends: btc
    #     container_name: btcd
    #     environment:
    #       - DEBUG
    #       - MINING_ADDRESS
    #     entrypoint: ["./start-btcd.sh"]

    # btcctl:
    #     extends: btc
    #     container_name: btcctl
    #     links:
    #         - "btcd:rpcserver"
    #     entrypoint: ["./start-btcctl.sh"]


    bitcoind:
      image: bitcoind
      build:
        context: bitcoind/
      volumes:
            - shared:/rpc
            - bitcoin:/bitcoin
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK

    # bitcoind:
    #     extends: btc
    #     container_name: bitcoind
    #     environment:
    #       - DEBUG
    #       - MINING_ADDRESS
    #     entrypoint: ["./start-bitcoind.sh"]


    # ltc is an image of litecoin node which used as base image for ltcd and
    # ltcctl. The environment variables default values determined on stage of
    # container start within startin

    lnd:
        image: lnd
        build:
          context: ../
          dockerfile: docker/lnd/Dockerfile
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
        volumes:
            - shared:/rpc
        entrypoint: ["./start-lnd.sh"]

    lnd_btc:
      extends: lnd
      container_name: lnd_btc
      links:
          - "bitcoind:blockchain"

volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  shared:
    driver: local

  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local
