apiVersion: batch/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Job
metadata:
  name: hellonode-job
spec:
  template:
    spec:
      containers:
      - name: hello-node
        image: hello-node:v3
        ports:
        - containerPort: 80
      restartPolicy: Never