apiVersion: batch/v1
kind: Job
metadata:
  name: hellonode-job
spec:
  template:
    spec:
      containers:
      - name: hello-node
        image: hello-node:v1
        ports:
        - containerPort: 80
      restartPolicy: Never
